# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2025-2026 ViralMint Contributors
from sqlalchemy import Column, String, Text, Integer, Float, DateTime, Boolean
from datetime import datetime
from uuid import uuid4
from backend.database import Base


class GeneratedVideo(Base):
    __tablename__ = "generated_videos"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid4()))
    user_id = Column(String(36), default="local", index=True)
    source_scout_result_id = Column(String(36), nullable=True)
    source_downloaded_video_id = Column(String(36), nullable=True)

    # Script + metadata
    title = Column(Text, nullable=True)
    script = Column(Text, nullable=True)
    niche = Column(String(200), nullable=True)

    # Files
    video_path = Column(Text, nullable=True)
    audio_path = Column(Text, nullable=True)
    thumbnail_path = Column(Text, nullable=True)

    # Generation params
    aspect_ratio = Column(String(10), default="9:16")    # 9:16 | 16:9
    duration_seconds = Column(Integer, nullable=True)
    voice_id = Column(String(100), nullable=True)
    gen_tier = Column(String(20), default="standard")    # standard | premium | clip_extraction
    source_type = Column(String(30), nullable=True)      # "clip_extraction" | null

    # Clip extraction fields
    clip_start_seconds = Column(Float, nullable=True)       # Start time in source video
    clip_end_seconds = Column(Float, nullable=True)         # End time in source video
    clip_virality_score = Column(Float, nullable=True)      # AI-scored 1-10
    clip_virality_reason = Column(Text, nullable=True)      # Why this clip is viral
    caption_status = Column(String(20), nullable=True)      # "applied" | "failed" | null
    metadata_status = Column(String(20), nullable=True)     # "ai_generated" | "fallback" | null

    # Upload tracking
    youtube_video_id = Column(String(50), nullable=True)
    tiktok_publish_id = Column(String(100), nullable=True)
    instagram_media_id = Column(String(100), nullable=True)
    uploaded_platforms_json = Column(Text, default="[]")  # ["youtube", "tiktok", "instagram"]
    video_path_landscape = Column(Text, nullable=True)   # 16:9 version (if exported)

    # Platform metadata (generated by AI for each platform)
    youtube_title = Column(Text, nullable=True)
    youtube_description = Column(Text, nullable=True)
    youtube_tags_json = Column(Text, nullable=True)
    tiktok_title = Column(Text, nullable=True)
    tiktok_description = Column(Text, nullable=True)

    # Cost tracking
    estimated_cost_usd = Column(Float, default=0.0)

    status = Column(String(20), default="draft")
    # statuses: draft | ready | uploading | uploaded | failed

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, onupdate=datetime.utcnow)
