name: sync

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Push to Hugging Face Space
        run: |
          git remote add hf https://huggingface.co/spaces/aoogoost/ViralMint
          git push hf main --force
